### ISSUE TITLE
Capture and send the name of the crashing thread

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-java#12]
Threads in Java have names, knowing which thread a crash occurred on can help with debugging. We should capture the name of the crashing thread and send that with the creash report.

See:
[Thread.UncaughtExceptionHandler#uncaughtException](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.UncaughtExceptionHandler.html#uncaughtException(java.lang.Thread, java.lang.Throwable))
[Thread#getName](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#getName())

**Comment by snmaynard** [comment]
I believe this is done!
