### ISSUE TITLE
Bugsnag-Spring & logback

### ISSUE THREAD

**Issue by sraveh** [bugsnag/bugsnag-java#132]
Hi,

Im trying to use bugsnag-spring 3.4.4 with spring boot 2.1.0. Im using log4j2 and not logback. Logback is excluded and not on the classpath. It seems that bugsnag-java is dependent on logback. Im getting the following error when the application start:

caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.bugsnag.BugsnagSpringConfiguration': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: ch/qos/logback/core/UnsynchronizedAppenderBase

**Comment by fractalwrench** [comment]
Thanks for the report @sraveh - this has been fixed in v3.4.6.
