### ISSUE TITLE
Steps to integrate Bugsnag to Java Openxava Web Framework

### ISSUE THREAD

**Issue by 92Harsha** [bugsnag/bugsnag-java#146]
Hi 

I am facing bit difficult in integrating bugsnag to one of my application its java OpenXava web framwork i have tried to follow the Java (https://docs.bugsnag.com/platforms/java/other/) documentation, my application is running using tomcat , it doesn't contain pom.xml, i can include the bugsnag jar in my application, now after including how do i define the bugsnag key and steps to automatically capture the exceptions and record in bugnsag.

I am using bugsnag for multiple applications. Please help me out in integrating to this application to.

Thank you.

**Comment by fractalwrench** [comment]
Hi @92Harsha - thanks for getting in touch. As this issue doesn't appear to be a problem/bug with the bugsnag-java library, it'd be best to contact support@bugsnag.com who can help you with your integration.

It sounds like you'd want to follow the [manual installation instructions](https://docs.bugsnag.com/platforms/java/other/#manual-jar-installation), followed by [basic configuration](https://docs.bugsnag.com/platforms/java/other/#basic-configuration) - support@bugsnag.com will be able to help you more if you're running into a problem with any of those steps.
