### ISSUE TITLE
Bugsnag prevents JVM from shutting down normally

### ISSUE THREAD

**Issue by smory** [bugsnag/bugsnag-java#151]
### Expected behavior
When all non daemon threads of any app  finish, the JVM shuts down normally... After implementing Bugsnag JVM still runs. This behavior is not what I expect, especially for AWT/Swing apps.

### Steps to reproduce
`public class Test {

    public static final void main(String[] args) {
        Bugsnag instance = new Bugsnag("api key");
    }
}`
JVM will never shut down...

### Version
3.6.1

### Additional information
If this cannot be fixed, please update your implementation guide to call System.exit(0) or bugsnag.close() somewhere in the code. Calling System.exit(0) is not common in AWT/Swing apps as user closes window and UI thread finishes normally.

This issue made our app update mechanism broken as JVM was running and old  jar couldn't be overwritten with new one. Also it made our app unusable after broken update as we use FileLock to enable single instance of app and and lock was never released as JVM kept running. This has broken around 100 installations of our app before we realized what has happened and stopped update. Unfortunately we didn’t discover this bug during our testing, only after it was released to production.

**Comment by mattdyoung** [comment]
Hi @smory 

Thanks for the report. Our team are just discussing the best way forward to resolve this issue.

**Comment by andybennett** [comment]
Possible solution would be to periodically check if there are any running deamon threads and if not call shutdown now on the sessionExecutorService.

Example of how to check threads using apache library
`
for (Thread t : ThreadUtils.getAllThreads()) {
      System.out.println(t.getName() + ", " + t.isDaemon());
}
`

**Comment by bootstraponline** [comment]
Hey, we just encountered this same issue at Robinhood. Is there an update on a fix?

**Comment by phillipsam** [comment]
Hi @bootstraponline thanks for letting us know! We do not currently have an eta for work on this. We will be sure to update back here when we have an update.

**Comment by nullobject** [comment]
I just got bitten by this issue in a Dataflow project, the Bugsnag logback appender was causing the process to hang.

Any updates?

**Comment by phillipsam** [comment]
Hi @nullobject no updates at present. We will be sure to update here when there are.

**Comment by johnkiely1** [comment]
This has now been fixed and released in [v3.6.2](https://github.com/bugsnag/bugsnag-java/releases/tag/v3.6.2)
