### ISSUE TITLE
Bugsnag.notify seems creating new HandshakeCompletedNotify-Thread each time

### ISSUE THREAD

**Issue by takaaki7** [bugsnag/bugsnag-java#175]
Profiling my application that is using bugsnag client(mainly using`Bugsnag.notify()`), bugsnag-async-deliver-%d thread seems creating many `HandshakeCompletedNotify-Thread`.

As I read code, it seems calling HttpURLConnection.disconnect() in SyncHttpDelivery.java  might be the cause.

https://github.com/bugsnag/bugsnag-java/blob/master/bugsnag/src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java#L111

https://bugs.openjdk.java.net/browse/JDK-8246039

A screenshot of a jfr profile of my app.
<img width="1640" alt="スクリーンショット 2022-02-16 16 40 19" src="https://user-images.githubusercontent.com/8406540/154218265-2573a5ce-a89e-4440-8f6e-cc8eecdc7ccd.png">

Is it able to reduce this new threads?

**Comment by xander-jones** [comment]
Hi @takaaki7, yes we think that's the same JDK bug that you're seeing here. There's no straightforward way that we can see for us to fix this in a way that is acceptable to all our users, I'm afraid hence why I'm marking this as `wontfix`.

However, the delivery mechanism in `bugsnag-java` is configurable. It's possible for you to provide your own `com.bugsnag.delivery.Delivery` instance that is tailored to your needs via [`Configuration.setDelivery`](https://docs.bugsnag.com/platforms/java/other/configuration-options/#setdelivery) and [`Configuration.setSessionDelivery`](https://docs.bugsnag.com/platforms/java/other/configuration-options/#setsessiondelivery). You could set the connection header to keep-alive or to use a different http library (e.g. the [Apache Http Client](https://hc.apache.org/httpcomponents-client-5.1.x/)).
