### ISSUE TITLE
Migrate to JakartaEE

### ISSUE THREAD

**Issue by lebenitza** [bugsnag/bugsnag-java#182]
With the upcoming release of spring 3.0, javax is dropped in favour of JakartaEE https://spring.io/blog/2022/10/20/spring-boot-3-0-0-rc1-available-now

Would be possible to have a major release version/separate branch of the library where this migration is done? I'll try to see if I can make the changes and test them locally.

**Comment by luke-belton** [comment]
Hi @lebenitza - thanks for raising this, we're going to look at support for Spring 3.0 and will keep you updated on this thread 👍

**Comment by pc-bob** [comment]
Any update on support for springboot 3.0?

**Comment by johnkiely1** [comment]
Hi @pc-bob, unfortunately no updates at the moment. This is still on our backlog. We will update here as soon as we have more information to share.

**Comment by gafful** [comment]
This may have to be prioritized a bit higher(perhaps treated as a bug) as it's causing Spring Boot 3+ apps to fail.

**Comment by SrMouraSilva** [comment]
There is a new release related to this https://github.com/bugsnag/bugsnag-java/releases/tag/v3.7.0
