### ISSUE TITLE
BugsnagServletContainerInitializer moved package during a minor version update

### ISSUE THREAD

**Issue by pilotclass** [bugsnag/bugsnag-java#195]
### Describe the bug

We use `BugsnagServletContainerInitializer` to initialise Bugsnag reporting in a Tomcat server.  We have followed [your advice](https://docs.bugsnag.com/platforms/java/other/#installation) and selected a version range `[3.0,4.0)` in our Maven build.  When you released version 3.7 of your java SDK, our builds broke, because the class has moved to another package.

Confirming with the semver specification, this change should entail a [major version increment](https://semver.org/#spec-item-8).

### Steps to reproduce

1. Set up a Java project using Maven, selecting version 3.6.4 of your Java SDK.
2. Use `BugsnagServletContainerInitializer` somewhere in that project, and ensure that it compiles.
3. Switch to the recommended version range `[3.0,4.0)` as specified in your [installation instructions](https://docs.bugsnag.com/platforms/java/other/#installation).
4. Try to compile the code

### Environment
* Bugsnag version: 3.7.0
* Java version: any

**Comment by johnkiely1** [comment]
Hi @pilotclass, 

Thanks for reporting this. Indeed the 3.7.0 release has caused some compatibility issues that we hadn't spotted beforehand. We're working out a way to make this fully backwards compatible and provide a follow-up release in due course, however in the meantime you will need to pin your dependency to 3.6.4. We'll update this thread when the new release is out. Apologies for the inconvenience.

**Comment by mclack** [comment]
Hi @pilotclass 

This issue has now been resolved in the [most recent release of bugsnag-java](https://github.com/bugsnag/bugsnag-java/releases/tag/v3.7.1). Please feel free to upgrade to version `3.7.1`, and let us know if you have any further issues.
