### ISSUE TITLE
3.7.0 is not available for java 8

### ISSUE THREAD

**Issue by XoddX** [bugsnag/bugsnag-java#196]
### Describe the bug
Latest version 3.7 is not available for java 8

### Steps to reproduce
1. Refresh your dependency to get 3.7 of bugsnag

### Environment
* Bugsnag version: 3.6.4
* Java version: 8
* Spring framework version : 5.3 (from Spring boot 2.6.1)
* Gradle version : 7.1.1

### Possible resolution
The 3.7 is build from docker env define by this Dockerfile for java 8 : [dockerfiles/Dockerfile.java8-mazerunner](https://github.com/bugsnag/bugsnag-java/blob/35eb2a6ff98fedd95b512e48eb3f99158bd1bf84/dockerfiles/Dockerfile.java8-mazerunner)

But the image used is `openjdk:17-jdk-slim`

**Comment by johnkiely1** [comment]
Hi @XoddX

Thanks for reporting this. Indeed the 3.7.0 release has caused some compatibility issues that we hadn't spotted beforehand. We're working out a way to make this fully backwards compatible and provide a follow-up release in due course, however in the meantime you will need to pin your dependency to 3.6.8. We'll update this thread when the new release is out. Apologies for the inconvenience.

**Comment by mclack** [comment]
Hi @XoddX 

This issue has now been resolved in the [most recent release of bugsnag-java](https://github.com/bugsnag/bugsnag-java/releases/tag/v3.7.1). Please feel free to upgrade to version `3.7.1`, and let us know if you have any further issues.
