### ISSUE TITLE
ExceptionHandler leaking

### ISSUE THREAD

**Issue by relnah** [bugsnag/bugsnag-java#27]
When undeploying application, Plumbr reports the following PermGen memory leak:

Leaked classloader
_org.apache.catalina.loader.WebappClassLoader_

The leaking classloader is being held
in _com.bugsnag.ExceptionHandler_
  in _defaultUncaughtExceptionHandler_ of _java.lang.Thread_
    in reference from native code (JNI global)

I create the bugsnag client via a static method in a final class. This is done during application startup.
I'm running Tomcat 7.0.64 with JVM 1.7.0_79-b15

**Comment by kattrali** [comment]
Thanks for the report, @relnah. Taking a look.

**Comment by llehtinen** [comment]
Came here to report the same.

If you add a call to ExceptionHandler.remove() in ServletContextListener.contextDestroyed() or something similar, the class loader will be eligible for GC. This solution is likely to be discovered the hard way, would be great if it could be avoided.

**Comment by KamBha** [comment]
@relnah 
Is there a fix for this in v3? The method (ExceptionHandler.remove) described above is not available in v3.

**Comment by KamBha** [comment]
@relnah 
I just noticed this class:-

https://github.com/bugsnag/bugsnag-java/blob/master/src/main/java/com/bugsnag/ExceptionHandler.java

I assume we need to call ExceptionHandler.disable?

Thanks.

Kamal.

**Comment by foygl** [comment]
Hi everyone,

The latest version of the Java notifier 3.0.1 now has a `close()` method which should attempt to clear up any resources that the notifier is using after the bean is finished with. Depending on what frameworks you are using, this may be a more or less manual process, for example if you use Spring and add Bugsnag as a managed bean, this will be called automatically when the bean is destroyed.

Let me know whether this solves or helps solve the issues reported here. If not it would be great if someone could supply a quick example app which does replicate this issue so we can investigate it further.

William

**Comment by KamBha** [comment]
@foygl 
Thanks.  Just want to confirm, you are talking about the close method on this class?

https://github.com/bugsnag/bugsnag-java/blob/master/src/main/java/com/bugsnag/Bugsnag.java

Thanks.

Kamal.

**Comment by foygl** [comment]
Yep - that's the one @KamBha
