### ISSUE TITLE
Bugsnag Warning

### ISSUE THREAD

**Issue by matiux** [bugsnag/bugsnag-java#39]
When I execute jar application in console I get this warning:

[Bugsnag] WARNING: Application terminated. 1 error(s) were not sent to Bugsnag

**Comment by kattrali** [comment]
Thank you for the report, @matiux. If an application terminates before any remaining reports are sent, this warning appears. Could you provide some additional details about your application and Java environment?

**Comment by matiux** [comment]
This is the method that I would like to handle with bugsnag whenthrown new NoUserException("No users");

```
    private static ArrayList<LandoUser> getActiveUsers(int userID) throws SQLException, NoUserException
    {
        Connection conn = dbConnection();
        ArrayList<LandoUser> users = new ArrayList<>();

        String specificUser = userID > 0 ? " AND u.id = " + userID : "";

        Statement stmt = conn.createStatement();
        ResultSet resultSet = stmt.executeQuery("SELECT u.id as user_id, i.id as imap_account_id" +
                                            " FROM users as u " +
                                            "JOIN user_imap_accounts as i ON u.id = i.user_id " +
                                            "WHERE active = 1" + specificUser);

        if (!resultSet.next() ) {

            throw new NoUserException("Nessun utente da elaborare");

        } else {

            do {

                users.add(new LandoUser(
                        resultSet.getInt("user_id"),
                        resultSet.getInt("imap_account_id")
                ));

            } while(resultSet.next());
        }



        resultSet.close();
        stmt.close();
        conn.close();

        return users;
    }
```

**Comment by kattrali** [comment]
@matiux When you exit the application, is it by interrupting it with Ctrl+C?

**Comment by kattrali** [comment]
Closing this one out, as I believe this was a case of the reporter running asynchronously and not having time to notify before the process terminated. The [example app](https://github.com/bugsnag/bugsnag-java/blob/master/example/java/src/main/java/example/Example.java) illustrates how to avoid this behavior when using Bugsnag solely for fatal error detection.
