### ISSUE TITLE
Add fatjar option to gradle build

### ISSUE THREAD

**Issue by twiggy** [bugsnag/bugsnag-java#71]
We are not really a java app, but it is deployed on top of Java and can consume JARs when 3rd party tools come into play.

We use a jar loader within the app to consume libraries that helps with any sort of accidental conflicts version or otherwise. So having simple one jar loads is easier for us.

Admittedly i haven't don Java work in a long long time so my gradle skills are just reading blog posts. 

I plopped this in the existing build.gradle file and ran it the custom task and got a .jar to my liking. I'd like to not have to do that each release, but I certainly can.

task customFatJar(type: Jar) {
    manifest {
    }
    baseName = 'all-in-one-jar'
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

all-in-one-jar would obviously be something more like bugsnag-all-in-one-${version}.jar

Thanks!

**Comment by fractalwrench** [comment]
Sorry for the delayed response @twiggy - a bugsnag JAR should be available for download [here](https://github.com/bugsnag/bugsnag-java/releases/latest), and can be integrated by following the [installation instructions](https://docs.bugsnag.com/platforms/java/other/#manual-jar-installation). Does that resolve your issue?
