### ISSUE TITLE
API v1 vs v2

### ISSUE THREAD

**Issue by besbes** [bugsnag/bugsnag-java#81]
We received a notification that Bugsnag will deprecate API v1 and asks to use v2 instead. When using the Java client, what needs to be done to keep the reporting up and running? Thanks!

**Comment by duncanhewett** [comment]
That notification relates to the [Data Access API](https://docs.bugsnag.com/api/data-access/) which is not connected to error reporting, so this Java library is unaffected.

**Comment by besbes** [comment]
Thanks for clarifying that @duncanhewett !
