### ISSUE TITLE
SyncHttpDelivery has possibliity to be throw NullPointerException

### ISSUE THREAD

**Issue by yonekawa** [bugsnag/bugsnag-java#91]
### Expected behavior
Do not throw NullPointerException

### Observed behavior
Sometime, SyncHttpDelivery throws NPE [here](https://github.com/bugsnag/bugsnag-java/blob/master/src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java#L100).

### Steps to reproduce
Sorry, I don't know reproduce steps.
I guess we had network problem(me or bugsnag) when I met the problem.
The problem produced at Aug 9th, 14:43:46 only once.

### Version
3.2.0

### Additional information
I think the problem is caused by [this code](https://github.com/bugsnag/bugsnag-java/blob/master/src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java#L58)

`connection` does not initialize If `URL#openConnection` throws `IOException`. However, [this code](https://github.com/bugsnag/bugsnag-java/blob/master/src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java#L100) tries `connection.disconnect()` in `finally` block.

**Comment by fractalwrench** [comment]
Thanks for the detailed report @yonekawa - it looks like there are a couple of scenarios where that could throw an NPE.
